name: "Build main"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
  KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
  GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
  CODE_COVERAGE_THRESHOLD: ${{ vars.CODE_COVERAGE_THRESHOLD }}

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v5.0.0

      - name: "Create Android emulator (phone profile) snapshot"
        uses: ./.github/actions/create-emulator-snapshot-action
        with:
          avd-profile: ${{ vars.AVD_PHONE_PROFILE }}
          avd-api-level: ${{ vars.AVD_API_LEVEL }}
          avd-target: ${{ vars.AVD_TARGET }}

      - name: "Create Android emulator (tablet profile) snapshot"
        uses: ./.github/actions/create-emulator-snapshot-action
        with:
          avd-profile: ${{ vars.AVD_TABLET_PROFILE }}
          avd-api-level: ${{ vars.AVD_API_LEVEL }}
          avd-target: ${{ vars.AVD_TARGET }}

      - name: "Set up development tools"
        uses: ./.github/actions/setup-dev-tools-action

      - name: "Assemble application"
        shell: bash
        run: ./gradlew assemble

      - name: "Run unit tests"
        uses: ./.github/actions/run-unit-tests-action

      - name: "Run instrumented tests (phone profile)"
        uses: ./.github/actions/run-instrumented-tests-action
        with:
          avd-profile: ${{ vars.AVD_PHONE_PROFILE }}
          avd-api-level: ${{ vars.AVD_API_LEVEL }}
          avd-target: ${{ vars.AVD_TARGET }}

      - name: "Run instrumented tests (tablet profile)"
        uses: ./.github/actions/run-instrumented-tests-action
        with:
          avd-profile: ${{ vars.AVD_TABLET_PROFILE }}
          avd-api-level: ${{ vars.AVD_API_LEVEL }}
          avd-target: ${{ vars.AVD_TARGET }}

      - name: "Code coverage"
        uses: ./.github/actions/code-coverage-action
        with:
          silent: true
