name: "Update Gradle Wrapper"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * MON" # Runs at 00:00 UTC every Monday

jobs:
  update-gradle-wrapper:
    name: "Update Gradle wrapper"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
      KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
      GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v5.0.0

      - name: "Set up development tools"
        uses: ./.github/actions/setup-dev-tools-action

      - name: "Update Gradle Wrapper"
        uses: gradle-update/update-gradle-wrapper-action@v2
        with:
          repo-token: ${{ secrets.GRADLE_WRAPPERBOT_PAT }}
